# Generated by Django 6.0.6 on 2026-06-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        ("payments", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.branch"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="staffcommission",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.branch"
            ),
        ),
        migrations.AddField(
            model_name="staffcommission",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="staffcommission",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="staffcommission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="payments_order_i_b32b33_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["branch", "status"], name="payments_branch__2395f1_idx"
            ),
        ),
    ]
