# Generated by Django 6.0.6 on 2026-06-29 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("pcs", "Pieces"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
            options={
                "db_table": "ingredients",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "Stock In"),
                            ("stock_out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                            ("waste", "Waste"),
                            ("theft_suspected", "Theft Suspected"),
                            ("order_consumption", "Order Consumption"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=25,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_movements",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("pcs", "Pieces"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recipes",
            },
        ),
    ]
