# Generated by Django 6.0.6 on 2026-06-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.branch",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="tenancy.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.branch"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.branch"
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_items",
                to="inventory.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_items",
                to="menu.product",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("branch", "ingredient"), name="uq_inventory_branch_ingredient"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["branch", "-created_at"], name="inventory_m_branch__25e378_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["ingredient", "-created_at"],
                name="inventory_m_ingredi_7f9365_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_m_movemen_a3c722_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("product", "ingredient"), name="uq_recipe_product_ingredient"
            ),
        ),
    ]
