# Generated by Django 6.0.6 on 2026-06-29 05:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_i18n",
                    models.JSONField(
                        help_text='e.g. {"uz": "Birinchi taomlar", "ru": "Супы", "en": "Soups"}'
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "menu categories",
                "db_table": "menu_categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_i18n",
                    models.JSONField(
                        help_text='e.g. {"uz": "Burger", "ru": "Бургер", "en": "Burger"}'
                    ),
                ),
                ("description_i18n", models.JSONField(blank=True, default=dict)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "prep_time_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "products",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
