# Generated by Django 6.0.6 on 2026-06-29 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = shared across all branches of this restaurant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="tenancy.branch",
            ),
        ),
        migrations.AddField(
            model_name="menucategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="tenancy.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = shared across all branches of this restaurant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenancy.branch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="menu.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenancy.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["restaurant", "branch"], name="menu_catego_restaur_856504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["restaurant", "branch"], name="products_restaur_6ea221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["branch", "is_available"], name="products_branch__1214a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
    ]
